"""
Italian stopwords for candidate filtering (Phase 2).

Version-controlled stopwords list for deterministic filtering.
Based on common Italian email greetings, closings, and generic terms.
"""

# Version for audit trail (update when list changes)
STOPLIST_VERSION = "stopwords-it-2025.1"

# Italian stopwords - comprehensive list
# Sources:
#   - Italian email conventions (Cordiali saluti, Distinti saluti)
#   - Common greetings (buongiorno, buonasera, arrivederci)
#   - Generic terms (grazie, prego, gentile)
#   - Standard Italian linguistics stopwords
STOPWORDS_IT = {
    # Email closings and greetings
    "grazie",
    "cordiali",
    "saluti",
    "distinti",
    "buongiorno",
    "buonasera",
    "ciao",
    "arrivederci",
    "salve",
    "gentile",
    "egregio",
    "spett",
    "cordialmente",
    "ringrazio",
    "ringraziamo",
    "ringraziandovi",
    "prego",
    # Common articles
    "il",
    "lo",
    "la",
    "i",
    "gli",
    "le",
    "un",
    "uno",
    "una",
    "l",
    # Prepositions and contractions
    "di",
    "a",
    "da",
    "in",
    "con",
    "su",
    "per",
    "tra",
    "fra",
    "del",
    "dello",
    "della",
    "dei",
    "degli",
    "delle",
    "al",
    "allo",
    "alla",
    "ai",
    "agli",
    "alle",
    "dal",
    "dallo",
    "dalla",
    "dai",
    "dagli",
    "dalle",
    "nel",
    "nello",
    "nella",
    "nei",
    "negli",
    "nelle",
    "sul",
    "sullo",
    "sulla",
    "sui",
    "sugli",
    "sulle",
    "col",
    "coi",
    # Common pronouns
    "io",
    "tu",
    "lui",
    "lei",
    "noi",
    "voi",
    "loro",
    "mi",
    "ti",
    "ci",
    "vi",
    "si",
    "me",
    "te",
    "se",
    "lo",
    "la",
    "li",
    "le",
    "gli",
    "ne",
    # Common verbs (essere, avere, fare in common forms)
    "è",
    "e",  # Also conjunction
    "sono",
    "sei",
    "siamo",
    "siete",
    "era",
    "erano",
    "stato",
    "stata",
    "stati",
    "state",
    "essere",
    "ho",
    "hai",
    "ha",
    "abbiamo",
    "avete",
    "hanno",
    "avere",
    "avuto",
    "avuta",
    "avuti",
    "avute",
    "fa",
    "fai",
    "fanno",
    "fare",
    "fatto",
    "fatta",
    "fatti",
    "fatte",
    # Conjunctions and adverbs
    "ed",
    "o",
    "od",
    "ma",
    "però",
    "pero",
    "quindi",
    "allora",
    "se",
    "che",
    "chi",
    "dove",
    "quando",
    "come",
    "perché",
    "perche",
    "anche",
    "ancora",
    "già",
    "gia",
    "mai",
    "sempre",
    "spesso",
    "molto",
    "più",
    "piu",
    "meno",
    "troppo",
    "tanto",
    "così",
    "cosi",
    "qui",
    "qua",
    "lì",
    "li",
    "là",
    "la",
    "poco",
    # Email-specific terms
    "email",
    "mail",
    "messaggio",
    "risposta",
    "oggetto",
    "inviato",
    "ricevuto",
    "allegato",
    "cc",
    "ccn",
    "bcc",
    "re",
    "fw",
    "fwd",
    "r",
    "inoltro",
    # Dates and time
    "oggi",
    "ieri",
    "domani",
    "ora",
    "adesso",
    "lunedì",
    "lunedi",
    "martedì",
    "martedi",
    "mercoledì",
    "mercoledi",
    "giovedì",
    "giovedi",
    "venerdì",
    "venerdi",
    "sabato",
    "domenica",
    "gennaio",
    "febbraio",
    "marzo",
    "aprile",
    "maggio",
    "giugno",
    "luglio",
    "agosto",
    "settembre",
    "ottobre",
    "novembre",
    "dicembre",
    # Numbers and quantifiers
    "uno",
    "due",
    "tre",
    "primo",
    "prima",
    "secondo",
    "seconda",
    "terzo",
    "terza",
    "tutti",
    "tutto",
    "tutte",
    "ogni",
    "qualche",
    "alcuni",
    "alcune",
    "altro",
    "altra",
    "altri",
    "altre",
    # Common words
    "cosa",
    "cosa",
    "suo",
    "sua",
    "suoi",
    "sue",
    "mio",
    "mia",
    "miei",
    "mie",
    "tuo",
    "tua",
    "tuoi",
    "tue",
    "nostro",
    "nostra",
    "nostri",
    "nostre",
    "vostro",
    "vostra",
    "vostri",
    "vostre",
    "questo",
    "questa",
    "questi",
    "queste",
    "quello",
    "quella",
    "quelli",
    "quelle",
    "stesso",
    "stessa",
    "stessi",
    "stesse",
    "tale",
    "tali",
    "quale",
    "quali",
}

# Additional patterns to filter (not in stopwords set but should be excluded)
# These are handled in filters.py via BLACKLIST_PATTERNS
